import { validateLevel } from "./logic";
import type { Direction, LevelConfig } from "./types";

const path = (value: string): Direction[] =>
  value
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((step) => {
      if (step === "U") return "up";
      if (step === "R") return "right";
      if (step === "D") return "down";
      if (step === "L") return "left";
      throw new Error(`Unknown direction token: ${step}`);
    });

export const LEVELS: LevelConfig[] = [
  {
    id: "level-01",
    name: "Blue Route",
    difficulty: 1,
    rows: 4,
    cols: 4,
    start: { row: 0, col: 0 },
    finish: { row: 2, col: 3 },
    targets: [
      { row: 1, col: 1 },
      { row: 2, col: 2 },
    ],
    solution: path("R D D R R"),
  },
  {
    id: "level-02",
    name: "Around the Gray",
    difficulty: 2,
    rows: 5,
    cols: 5,
    start: { row: 4, col: 0 },
    finish: { row: 0, col: 4 },
    targets: [
      { row: 3, col: 1 },
      { row: 1, col: 3 },
    ],
    blockers: [
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 3 },
    ],
    solution: path("U R D R R R U U U L U R"),
  },
  {
    id: "level-03",
    name: "Horizontal Pipe",
    difficulty: 3,
    rows: 5,
    cols: 6,
    start: { row: 2, col: 0 },
    finish: { row: 2, col: 5 },
    targets: [{ row: 2, col: 4 }],
    blockers: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
    ],
    pipes: [
      { point: { row: 2, col: 2 }, shape: "horizontal" },
      { point: { row: 2, col: 3 }, shape: "horizontal" },
    ],
    solution: path("R R R R R"),
  },
  {
    id: "level-04",
    name: "Vertical Pipe",
    difficulty: 4,
    rows: 6,
    cols: 5,
    start: { row: 5, col: 2 },
    finish: { row: 0, col: 2 },
    targets: [{ row: 1, col: 2 }],
    blockers: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 5, col: 0 },
      { row: 5, col: 1 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
    ],
    pipes: [
      { point: { row: 2, col: 2 }, shape: "vertical" },
      { point: { row: 3, col: 2 }, shape: "vertical" },
    ],
    solution: path("U U U U U"),
  },
  {
    id: "level-05",
    name: "First Bend",
    difficulty: 5,
    rows: 5,
    cols: 5,
    start: { row: 0, col: 0 },
    finish: { row: 4, col: 4 },
    targets: [
      { row: 1, col: 3 },
      { row: 3, col: 2 },
    ],
    blockers: [
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 4, col: 2 },
    ],
    pipes: [{ point: { row: 1, col: 2 }, shape: "curve-dl" }],
    solution: path("R D R D D R U U R D D D"),
  },
  {
    id: "level-06",
    name: "Mixed Ports",
    difficulty: 6,
    rows: 5,
    cols: 6,
    start: { row: 2, col: 0 },
    finish: { row: 2, col: 5 },
    targets: [
      { row: 0, col: 4 },
      { row: 4, col: 1 },
    ],
    blockers: [
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 3, col: 3 },
      { row: 4, col: 3 },
      { row: 4, col: 5 },
    ],
    pipes: [
      { point: { row: 2, col: 2 }, shape: "curve-rd" },
      { point: { row: 2, col: 3 }, shape: "horizontal" },
    ],
    solution: path("D D R R U U R R U U R D D"),
  },
  {
    id: "level-07",
    name: "Rotating Straight",
    difficulty: 7,
    rows: 3,
    cols: 5,
    start: { row: 0, col: 0 },
    finish: { row: 1, col: 4 },
    targets: [{ row: 1, col: 3 }],
    blockers: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
    ],
    rotators: [{ row: 1, col: 0 }],
    pipes: [{ point: { row: 1, col: 2 }, shape: "vertical" }],
    solution: path("D R R R R"),
  },
  {
    id: "level-08",
    name: "Rotating Bend",
    difficulty: 8,
    rows: 5,
    cols: 5,
    start: { row: 0, col: 0 },
    finish: { row: 4, col: 4 },
    targets: [{ row: 4, col: 2 }],
    blockers: [
      { row: 0, col: 1 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 2, col: 3 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
    ],
    rotators: [{ row: 1, col: 0 }],
    pipes: [{ point: { row: 2, col: 2 }, shape: "curve-rd" }],
    solution: path("D D R R D D R R"),
  },
  {
    id: "level-09",
    name: "Three Beacons",
    difficulty: 9,
    rows: 6,
    cols: 6,
    start: { row: 5, col: 0 },
    finish: { row: 0, col: 1 },
    targets: [
      { row: 5, col: 3 },
      { row: 2, col: 4 },
      { row: 0, col: 2 },
    ],
    blockers: [
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 3, col: 2 },
      { row: 1, col: 3 },
      { row: 2, col: 2 },
      { row: 5, col: 4 },
    ],
    pipes: [{ point: { row: 4, col: 3 }, shape: "vertical" }],
    solution: path("R R R U U U R U U L L L"),
  },
  {
    id: "level-10",
    name: "Zigzag Corridor",
    difficulty: 10,
    rows: 6,
    cols: 6,
    start: { row: 0, col: 5 },
    finish: { row: 5, col: 0 },
    targets: [
      { row: 1, col: 1 },
      { row: 4, col: 4 },
    ],
    blockers: [
      { row: 0, col: 2 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 3 },
      { row: 5, col: 5 },
    ],
    pipes: [
      { point: { row: 1, col: 3 }, shape: "curve-lu" },
      { point: { row: 4, col: 2 }, shape: "horizontal" },
      { point: { row: 4, col: 3 }, shape: "horizontal" },
    ],
    solution: path("L L D L L D D D R R R D L L L L"),
  },
  {
    id: "level-11",
    name: "Double Rotation",
    difficulty: 11,
    rows: 6,
    cols: 6,
    start: { row: 3, col: 0 },
    finish: { row: 0, col: 5 },
    targets: [
      { row: 5, col: 2 },
      { row: 1, col: 4 },
    ],
    blockers: [
      { row: 2, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 4, col: 2 },
      { row: 2, col: 3 },
      { row: 1, col: 3 },
    ],
    rotators: [
      { row: 4, col: 0 },
      { row: 5, col: 4 },
    ],
    pipes: [
      { point: { row: 5, col: 1 }, shape: "vertical" },
      { point: { row: 3, col: 4 }, shape: "vertical" },
    ],
    solution: path("D D R R R R U U U U U R"),
  },
  {
    id: "level-12",
    name: "Terminal Matrix",
    difficulty: 12,
    rows: 6,
    cols: 6,
    start: { row: 0, col: 0 },
    finish: { row: 5, col: 5 },
    targets: [
      { row: 0, col: 5 },
      { row: 5, col: 0 },
      { row: 3, col: 3 },
    ],
    blockers: [
      { row: 0, col: 2 },
      { row: 1, col: 2 },
      { row: 2, col: 2 },
      { row: 3, col: 2 },
      { row: 4, col: 2 },
      { row: 2, col: 4 },
      { row: 4, col: 3 },
    ],
    rotators: [{ row: 1, col: 1 }],
    pipes: [
      { point: { row: 5, col: 2 }, shape: "vertical" },
      { point: { row: 5, col: 3 }, shape: "vertical" },
    ],
    solution: path(
      "D R D D D L D R R R R U U L U U U R R D D D D D",
    ),
  },
];

LEVELS.forEach(validateLevel);

export const getLevelById = (levelId: string) =>
  LEVELS.find((level) => level.id === levelId) ?? LEVELS[0];

export const getNextLevel = (levelId: string) => {
  const index = LEVELS.findIndex((level) => level.id === levelId);
  return LEVELS[(index + 1) % LEVELS.length];
};
