export const settingsRoute = {
  segment: {
    root: "settings",
    account: "account",
    personalization: "personalization",
    search: "search",
    thirdParty: "third-party",
    language: "language",
    backup: "backup",
    about: "about",
    developer: "developer",
    wildcard: "*",
  },
  path: {
    root: "/settings",
    account: "/settings/account",
    personalization: "/settings/personalization",
    search: "/settings/search",
    thirdParty: "/settings/third-party",
    language: "/settings/language",
    backup: "/settings/backup",
    about: "/settings/about",
    developer: "/settings/developer",
  },
} as const;
