import {
  RiBrushFill,
  RiBrushLine,
  RiCodeSSlashFill,
  RiCodeSSlashLine,
  RiGlobalFill,
  RiGlobalLine,
  RiInbox2Fill,
  RiInbox2Line,
  RiInformationFill,
  RiInformationLine,
  RiSearchFill,
  RiSearchLine,
  RiSettings3Line,
  RiUserFill,
  RiUserLine,
} from "@remixicon/react";
import type { DefaultAppRouteDefinition } from "../route-config";
import { settingsRoute } from "./route-paths";

export const settingsRootRouteDefinition: DefaultAppRouteDefinition = {
  key: "settings.root",
  segment: settingsRoute.segment.root,
  path: settingsRoute.path.root,
  meta: {
    title: "设置",
    description: "管理账号、外观、搜索、语言与备份",
    icon: <RiSettings3Line size={16} />,
    keywords: ["settings", "preferences", "系统设置"],
  },
  sidebar: false,
  search: false,
};

export const settingsRouteDefinitions: DefaultAppRouteDefinition[] = [
  {
    key: "settings.account",
    segment: settingsRoute.segment.account,
    path: settingsRoute.path.account,
    meta: {
      title: "账号",
      description: "账号资料、登录与安全",
      icon: <RiUserLine size={16} />,
      activeIcon: <RiUserFill size={16} />,
      keywords: ["user", "account", "profile", "login", "安全"],
    },
    sidebar: { enabled: true },
    search: { enabled: true, group: "setting" },
  },
  {
    key: "settings.account-profile",
    segment: settingsRoute.segment.accountProfile,
    path: settingsRoute.path.accountProfile,
    meta: {
      title: "个人资料",
      description: "编辑用户名",
      keywords: ["user", "account", "profile", "username", "个人资料"],
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.account-security",
    segment: settingsRoute.segment.accountSecurity,
    path: settingsRoute.path.accountSecurity,
    meta: {
      title: "登录与安全",
      description: "修改密码或删除账号",
      keywords: ["password", "security", "delete account", "密码", "注销"],
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.personalization",
    segment: settingsRoute.segment.personalization,
    path: settingsRoute.path.personalization,
    meta: {
      title: "个性化",
      description: "外观、主题与桌面背景",
      icon: <RiBrushLine size={16} />,
      activeIcon: <RiBrushFill size={16} />,
      keywords: [
        "theme",
        "wallpaper",
        "appearance",
        "zen",
        "focus",
        "背景",
        "主题",
        "禅模式",
        "专注模式",
        "极简",
      ],
    },
    sidebar: { enabled: true },
    search: { enabled: true, group: "setting" },
  },
  {
    key: "settings.search",
    segment: settingsRoute.segment.search,
    path: settingsRoute.path.search,
    meta: {
      title: "搜索",
      description: "桌面搜索框与键盘呼出",
      icon: <RiSearchLine size={16} />,
      activeIcon: <RiSearchFill size={16} />,
      keywords: ["spotlight", "keyboard", "shortcut", "搜索框", "快捷键"],
    },
    sidebar: { enabled: true },
    search: { enabled: true, group: "setting" },
  },
  {
    key: "settings.language",
    segment: settingsRoute.segment.language,
    path: settingsRoute.path.language,
    meta: {
      title: "语言",
      description: "界面语言",
      icon: <RiGlobalLine size={16} />,
      activeIcon: <RiGlobalFill size={16} />,
      keywords: ["language", "locale", "中文", "英文"],
    },
    sidebar: { enabled: true },
    search: { enabled: true, group: "setting" },
  },
  {
    key: "settings.backup",
    segment: settingsRoute.segment.backup,
    path: settingsRoute.path.backup,
    meta: {
      title: "备份与恢复",
      description: "本地备份、云备份与数据恢复",
      icon: <RiInbox2Line size={16} />,
      activeIcon: <RiInbox2Fill size={16} />,
      keywords: ["backup", "restore", "sync", "备份", "恢复"],
    },
    sidebar: { enabled: true },
    search: { enabled: true, group: "setting" },
  },
  {
    key: "settings.backup-storage",
    segment: settingsRoute.segment.backupStorage,
    path: settingsRoute.path.backupStorage,
    meta: {
      title: "云备份存储",
      description: "查看云备份空间与版本",
      keywords: ["backup", "storage", "sync", "存储", "云备份"],
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.backup-storage-apps",
    segment: settingsRoute.segment.backupStorageApps,
    path: settingsRoute.path.backupStorageApps,
    meta: {
      title: "应用占用",
      description: "查看各应用的本地数据占用",
      keywords: ["apps", "storage", "应用占用"],
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.backup-storage-detail",
    segment: settingsRoute.segment.backupStorageDetail,
    path: `${settingsRoute.path.backupStorage}/:backupId`,
    meta: {
      title: "云备份详情",
      description: "查看备份版本详情",
      keywords: ["backup", "detail", "备份详情"],
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.about",
    segment: settingsRoute.segment.about,
    path: settingsRoute.path.about,
    meta: {
      title: "关于",
      description: "版本与项目说明",
      icon: <RiInformationLine size={16} />,
      activeIcon: <RiInformationFill size={16} />,
      keywords: ["about", "version", "版本"],
    },
    sidebar: { enabled: true },
    search: { enabled: true, group: "setting" },
  },
  {
    key: "settings.about-releases",
    segment: settingsRoute.segment.aboutReleases,
    path: settingsRoute.path.aboutReleases,
    meta: {
      title: "版本记录",
      description: "查看历史版本更新",
      keywords: ["release", "version", "history", "版本记录"],
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.about-release-detail",
    segment: settingsRoute.segment.aboutReleaseDetail,
    path: settingsRoute.path.aboutReleaseDetail,
    meta: {
      title: "版本详情",
      description: "查看版本更新内容",
      keywords: ["release", "version", "版本详情"],
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.about-terms",
    segment: settingsRoute.segment.aboutTerms,
    path: settingsRoute.path.aboutTerms,
    meta: {
      title: "服务条款",
      description: "查看当前服务条款",
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.about-privacy",
    segment: settingsRoute.segment.aboutPrivacy,
    path: settingsRoute.path.aboutPrivacy,
    meta: {
      title: "隐私政策",
      description: "查看当前隐私政策",
    },
    sidebar: false,
    search: false,
  },
  {
    key: "settings.developer",
    segment: settingsRoute.segment.developer,
    path: settingsRoute.path.developer,
    meta: {
      title: "开发者",
      description: "应用开发入口",
      icon: <RiCodeSSlashLine size={16} />,
      activeIcon: <RiCodeSSlashFill size={16} />,
      keywords: ["dev", "app", "esm", "开发", "应用"],
    },
    sidebar: { enabled: true },
    search: { enabled: true, group: "setting" },
  },
];
