/**
 * 本地存储桌面配置 key
 */
export const DESKTOP_LIST_STORAGE_KEY = "SEARCH_NEXT_DESKTOP_LIST";
/**
 * 用户是否修改过桌面配置
 */
export const DESKTOP_LIST_MODIFIED_STORAGE_KEY =
  "SEARCH_NEXT_DESKTOP_LIST_MODIFIED";

export const DESKTOP_THEME_STORAGE_KEY = "SEARCH_NEXT_DESKTOP_THEME";

export const PERSONALIZATION_STORAGE_KEY = "SEARCH_NEXT_PERSONALIZATION";

/**
 * 已读通知 id 列表
 */
export const NOTICE_READ_IDS_STORAGE_KEY = "SEARCH_NEXT_NOTICE_READ_IDS";
